### ISSUE TITLE
如何解决0->auto的transition动画

### ISSUE THREAD

**Issue by 0x7h11s** [xlearns/myblog#168]
- css规范明确 transition 不支持 height: auto
  - 
  ```css
     {
      &.up {
          height: 0;
      }
      &.down {
        - height: unset;
        + height: 500px;
      }
  }
   ``` 
-  巧用max-height适配动态高度
  -  如果容器实际高度只有 200px，max-height为 1000px，动画时间为 1s，缓动函数为 linear。实际动画从 0 到 200px 的高度过渡时间只有 0.2s，这一点需要非常注意~
       因为本来展开动画是期望将容器的高度用 1s 的时间拉伸至 1000px，实际在 200px 的时候就停止了，所以动画时间只有 0.2 秒。
  ```ccs
    {
        max-height: 0;
        transition: max-height 0.3s linear;
     
        &.up {
            max-height: 0;
        }
        &.down {
            max-height: 1000px;
        }
    }
   ``` 

# demo
```vue
<script setup>
import { ref,isRef,isReactive,reactive } from 'vue'
const test =ref(false)
function click(){
  test.value = !test.value
}
window.addEventListener('click',()=>{
  click()
})
</script>

<template>
   <div class='box' :class="{test:test}">
  </div>
</template>
<style>
  .box{
    max-width:0px;
    height:500px;
    background:red;
    transition:all 0.3s;
  }
  .test{
    max-width:100px;
  }
</style>
```
