### ISSUE TITLE
css隐藏滚动条

### ISSUE THREAD

**Issue by 0x7h11s** [xlearns/myblog#182]
# element plus
##  隐藏滚动条
```scss
      .context{
         scrollbar-width: none;
        &::-webkit-scrollbar {
          display: none;
        }
     }
```
