### ISSUE TITLE
css linear-gradient

### ISSUE THREAD

**Issue by 0x7h11s** [xlearns/myblog#248]
- 第一个参数为终点，对角线为起始点，因为要满足线性
```css
<style>
#grad1 {
    height: 200px;
    background: linear-gradient(to bottom right, #fff 49.9%,red 50%,red 100% );
}
</style>
<div id="grad1"></div>
```
